---
- name: Run the equivalent of "pacman -Syu" as a separate step.
  community.general.pacman:
    update_cache: true
    upgrade: true
  become: true

- name: Install pacman packages.
  community.general.pacman:
    name:
      "{{ \
        lookup(\
          'ansible.builtin.vars',\
          'list_of_' + type + '_packages',\
          default=''\
        ) \
      }}"
    state: present
  when: >-
    lookup(
      'ansible.builtin.vars',
      'install_' + type + '_packages',
      default='false'
    ) is truthy(convert_bool=True)
    and
    lookup(
      'ansible.builtin.vars',
      'list_of_' + type + '_packages',
      default=''
    ) | length > 0
  loop: "{{ package_types }}"
  loop_control:
    loop_var: type
  become: true
