---
# - name: Run the equivalent of "apt update" as a separate step.
#   apt:
#     update_cache: true
#   become: true

- name: Install apt packages.
  apt:
    name: "{{ lookup('ansible.builtin.vars', 'list_of_' + type + '_packages', default='') }}"
    state: present
  when: lookup('ansible.builtin.vars', 'install_' + type + '_packages', default='false') is truthy(convert_bool=True)
  loop: "{{ package_types }}"
  loop_control:
    loop_var: type
  become: true

- name: Install snap packages
  snap:
    name: "{{ lookup('ansible.builtin.vars', 'list_of_' + type + '_snap_packages', default='') }}"
    state: present
    classic: true
  when: lookup('ansible.builtin.vars', 'install_' + type + '_snap_packages', default='false') is truthy(convert_bool=True)
  loop: "{{ package_types }}"
  loop_control:
    loop_var: type
  become: true


# - name: Gather package facts.
#   package_facts:
#     manager: apt
#
# - name: Debugging.
#   debug:
#     var: ansible_facts.packages["neovim"][0]["version"]
#
# - include_tasks: install_neovim.yml
#   when: '"neovim" not in ansible_facts.packages
#         or ansible_facts.packages["neovim"][0]["version"]
#         is version(neovim_minimal_required_version, "<")'
