---
- name: Include OS-specific variables.
  ansible.builtin.include_vars: list_of_{{ ansible_os_family }}_packages.yml

- name: Include OS-specific tasks.
  ansible.builtin.include_tasks: install_{{ ansible_os_family }}_packages.yml
